Repository AY2425S1-CS2103T-F08-1a/tp, pull requests merged in 2024-10, with the labels that each got.

#45 Add new command to view person details
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/resources/view/CommandBox.css
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#46 Update edit command to match new Person fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#50 Fix not saving to storage bug
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Bug, priority.High, severity.Medium

#63 Add "vtc" command to display bar charts of total hours tutored per tutee
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewTuteeChartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Hours.java
  src/main/java/seedu/address/ui/ChartWindow.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/ChartWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Story, priority.Medium

#65 Fix edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug

#87 Update parser
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddTuteeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutorCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/storage/CsvImport.java
  src/test/java/seedu/address/logic/parser/AddTutorCommandParserTest.java
Labels: priority.High

#102 Add UML for ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Medium
