Repository AY2425S1-CS2103T-F08-1a/tp, pull requests merged in 2024-11, with the labels that each got.

#111 Add Subject to Lesson.java
  src/main/java/seedu/address/logic/commands/AddLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewTutorChartCommand.java
  src/main/java/seedu/address/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/ChartWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#118 Fix CsvImport tests
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/storage/CsvImport.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/CsvImportTest/duplicatePersonsCsv.csv
  src/test/data/CsvImportTest/extraHeadersCsv.csv
  src/test/data/CsvImportTest/extraRowsCsv.csv
  src/test/data/CsvImportTest/failedPersonsCsv.csv
  src/test/data/CsvImportTest/missingHeadersCsv.csv
  src/test/data/CsvImportTest/missingRowsCsv.csv
  src/test/data/CsvImportTest/typicalPersonsCsv.csv
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Enhancement, type.Bug

#154 Fix import bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedSubjectConverter.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/AddTutorCommandParserTest.java
Labels: alpha-bug

#188 Edit DeveloperGuide.md and UserGuide.md
  docs/DeveloperGuide.md
  docs/site.json
Labels: type.Enhancement

#293 Fix images
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/UiOverview.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High
